title: My Website
email: 42piyush@gmail.com
description: > 
  This is my personal website hosted on GitHub Pages.
baseurl: "/homepage"               # the subpath of your site, e.g., /blog
url: "https://piyush42.github.io" # the base hostname & protocol for your site
twitter_username: johndoe
github_username: yourusername

# Build settings
theme: minima
plugins:
  - jekyll-feed
