title: Piyush Varanjani
description: This is my personal website hosted on GitHub Pages.
baseurl: "/homepage"
url: "https://piyush42.github.io"

# Build settings
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Navigation links
nav_links:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Projects"
    link: "/projects"
  - name: "Essays"
    link: "/essays"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
